name = "gbr_ui_storybook"
description = "GBR: UI Storybook Library"
version = "1.0.1"
target = "javascript"
gleam = ">=1.17.0"

repository = { type = "github", user = "gleam-br", repo = "gbr_ui_storybook" }
licences = ["Apache-2.0"]
links = []

[dependencies]
gleam_stdlib = "~> 1.0"

lustre = "~> 5.7"

[dev-dependencies]
gleeunit = "~> 1.11"

[javascript]
typescript_declarations = true
